name: poly
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - ace-tools==0.0
      - appnope==0.1.4
      - asttokens==3.0.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filterpy==1.4.5
      - fonttools==4.56.0
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - looseversion==1.3.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - numpy==2.0.2
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.7
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - tdqm==0.0.1
      - threadpoolctl==3.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - trackpy==0.6.4
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - wcwidth==0.2.13
      - zipp==3.21.0